application: snipperize
version: 1
runtime: python
api_version: 1

handlers:
#- url: /static
#  static_dir: static

  
- url: /favicon.ico
  static_files: media/img/favicon.ico
  upload: media/img/favicon.ico
  mime_type: image/x-icon

- url: /robots.txt
  static_files: media/robots.txt
  upload: media/robots.txt

- url: /.*
  script: main.py
